### ISSUE TITLE
Write a guide: Git Flow for Contributors 

### ISSUE THREAD

**Issue by Jaykul** [PoshCode/ModuleBuilder#1]
We need one of [these](https://guides.github.com/introduction/flow/) for git flow, showing the happy path for new contributors.

Unlike _every other_ git flow document on the internet, it _should not_ mention releases or hotfixes, but instead document a process exactly the same as [github flow](https://guides.github.com/introduction/flow/), except working against the "develop" branch instead of "master" and changing the **ProTip** on the first page to explain that you're contributing to the development branch because the master branch represents already released content.

**Comment by daviwil** [comment]
+1

**Comment by Jaykul** [comment]
Should we consider [CommonFlow](https://commonflow.org/) and [OneFlow](http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow) as alternatives?

**Comment by michaeltlombardi** [comment]
Definitely should consider something like CommonFlow as well. Strong preference for releases identified as tags on commits and fewer long lived branches.

**Comment by Jaykul** [comment]
I think we've moved past the notion of using the `develop` branch as the merge target. Instead, we'll tag releases and merge to master -- like everyone else.

Because of that, I'll open a new issue later requesting a doc based on `CommonFlow` and discussing semver (perhaps [this experiment](https://gist.github.com/Jaykul/5687dc25b081e61e41de2a5635b506aa) can be of some use there)...

**Comment by michaeltlombardi** [comment]
I'd be happy to review/contribute to the `CommonFlow` docs, but couldn't commit to owning them for a bit (wedding upcoming).

**Comment by Jaykul** [comment]
We obviously didn't need this as badly as I thought we did.
