### ISSUE TITLE
Bootstrap discussion - Install vs Save module

### ISSUE THREAD

**Issue by gaelcolas** [PoshCode/ModuleBuilder#10]
Not an issue, just a discussion to see what you have in mind.

I find that installing modules, even in the `CurrentUser` scope, leads to annoying issues. As an example, the `-SkipPublisherCheck` and `-AllowClobber` issues when trying to build `ModuleBuilder` on a vanilla Windows 10 machine. Package management is another problem, by default you get 1.0.0.1 which is not great and creates some problems (I think with PSDepend, iirc, not even mentioning DSC).

I also find it easier when all dependencies are only local to the project (in the `output` folder), so that you have less _variables_ from environment to environment (i.e. DEV box to CI agent), and thus for troubleshooting. I even usually go the extra mile to change the `$PSModulePath` to `$PSHome` plus the downloaded dependencies, to limit where modules are loaded from. When you have DSC managing systems it's hard to be sure what's available and can change from one run to another.

Most of this would be dealt by PSDepend by adding a `target = ".\Output\modules"` or similar in the options, but we'd probably need to also enable this for the bootstrap script (which I'll open a separate issue for).
We'd also have to change the $Env:PSModulePath to, at least, add the resolved path where dependencies are downloaded.
This should probably be optional, and could be handled by a parameter, and set in the `Build.psd1`.

Would you consider this option? What do you think?

----
Error building ModuleBuilder on (almost) vanilla Windows 10, PS 5.1.

```PowerShell
PS C:\src\ModuleBuilder> .\build.ps1 -Verbose
VERBOSE: BUILDING ModuleBuilder VERSION 1.0.0
VERBOSE: Bootstrap hack for building ModuleBuilder with ModuleBuilder
WARNING: The verb 'Build' was approved recently, but PowerShell 5.1 doesn't know. You will be warned about
Build-Module
VERBOSE: The 'Build-Module' command in the ModuleBuilderBootStrap' module was imported, but because its name
does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "New".
VERBOSE: Importing function 'Build-Module'.
VERBOSE: Importing function 'Convert-CodeCoverage'.
VERBOSE: Importing function 'Convert-LineNumber'.
WARNING: The names of some imported commands from the module 'ModuleBuilderBootStrap' include unapproved verbs  that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module
command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
VERBOSE: Populating RepositorySourceLocation property for module PSDepend.
VERBOSE: Loading module from path
'C:\Users\GaelColas\Documents\WindowsPowerShell\Modules\PSDepend\0.2.3\PSDepend.psm1'.
PackageManagement\Install-Package : The version '4.4.0' of the module 'Pester' being installed is not catalog
signed. Ensure that the version '4.4.0' of the module 'Pester' has the catalog file 'Pester.cat' and signed
with the same publisher 'CN=Microsoft Development Root Certificate Authority 2014, O=Microsoft Corporation,
L=Redmond, S=Washington, C=US' as the previously-installed module '4.4.0' with version '3.4.0' under the
directory 'C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0'. If you still want to install or update,
use -SkipPublisherCheck parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-P
   ackage], Exception
    + FullyQualifiedErrorId : ModuleIsNotCatalogSigned,Validate-ModuleAuthenticodeSignature,Microsoft.PowerSh
   ell.PackageManagement.Cmdlets.InstallPackage
```

**Comment by Jaykul** [comment]
Is there any other language or tool framework where you would actually install your build tools locally into _every_ project? That sounds... crazy.

I think you have a little frustration with your package management tool, and you're trying to solve it by over-architecting your build process instead of fixing the so-called `-SkipPublisherCheck` and `-AllowClobber` "issues" which are [**clearly** just a **BUG** in PowerShellGet](https://github.com/PowerShell/PowerShellGet/issues/234). That's not a problem **PowerShell** has, or ModuleBuilder module has. It's a problem with PowerShellGet. 

I actually think the workaround for now is just to put those switches into your `$PSDefaultParameterValues` and stop worrying 🤪

**Comment by gaelcolas** [comment]
Touché for the frustration with the Package Management tool...

That said, it's unlikely that ModuleBuilder will be the only 'tool' needed (i.e. Plaster, BuildHelpers, and who knows what), and it makes debugging simpler when it's all within the repo, so I think it's a valuable *option* (I've had very good feedback on this feature of SampleModule, and crucial when you want *anyone* to be able to bootstrap your build without fixing their environment).

The only change to have this supported is in the bootstrap script to allow Saving PSDepend instead of Installing, and allow changing the $PSModulePath before running `Build-Module`.

Also, it's pretty much a Requirement for DSC IMO, as you need to limit the variables or you can have some weirdness into what is used when composite don't specify versions for example (and you could  rightly argue again that it's a PSDesiredStateConfiguration.psm1 bug... but eh, that's what we're dealing with).

**Comment by Jaykul** [comment]
Conceptually, I have no problem with that as an option -- send a PR?
