### ISSUE TITLE
Boolean with psd1 is not being parsed correctly when Configuration 1.5/Metadata 1.5 are installed.

### ISSUE THREAD

**Issue by MaxFrost** [PoshCode/ModuleBuilder#106]
This is mostly informational - Due to a recent change to the Configuration required module, there is a secondary required module, Metadata, that is causing boolean values within the build.psd1 to be incorrectly propagated. See https://github.com/PoshCode/Metadata/issues/1 for more details.

When that issue is resolved, this issue should also resolve.

**Comment by MaxFrost** [comment]
In my case, I was utilizing `VersionedOutputDirectory = $true` in my build.psd1s in a CI pipeline, and suddenly lost the versioned output, which broke publish steps later that were expecting versioned folder output. Workaround was to upgrade to ModuleBuilder 2.0 and remove the boolean from the psd1.

**Comment by MaxFrost** [comment]
Alternative workaround is to remove Configration 1.5 and Metadata 1.5, and install Configuration 1.3.

**Comment by Jaykul** [comment]
This should work in Metadata 1.5.1 -- sorry about that!
