### ISSUE TITLE
Add support to order PS1 when file system doesn't

### ISSUE THREAD

**Issue by gaelcolas** [PoshCode/ModuleBuilder#118]
On Azure DevOps (ubuntu-latest MSFT hosted agents) the PowerShell lists the files in order but not the subfolders (at least not always).
This creates psm1 that are unparseable for pwsh because the Class definition is not in order (inherited class defined before parent).
This happens when `classes/` folder is further divided in subfolders (DSC Resources, GC Resources, Category1, Category2...).
![image](https://user-images.githubusercontent.com/8962101/220657266-f3836d38-4658-4f2a-b213-98d7ab83973a.png)

Question, can we have a "custom sorter"?

**Comment by Jaykul** [comment]
Well, I think you _could_ list each subfolder in `SourceDirectories` in order, and it would work..

Currently, that code looks like:
```pswh
Get-ChildItem -Path @($ModuleInfo.SourceDirectories).ForEach{ Join-Path $ModuleInfo.ModuleBase $_ } -Filter *.ps1 -Recurse -ErrorAction SilentlyContinue
```

I guess we could add `| Sort-Object Fullname` and that would take care of it?

**Comment by gaelcolas** [comment]
Draft PR coming in shortly... :)
The question will be, shall we mandate the sorting (as per your example), or leave us to provide the `-Property` to `Sort-Object`...

**Comment by gaelcolas** [comment]
Completed a while ago.
