### ISSUE TITLE
Line incorrectly references module

### ISSUE THREAD

**Issue by kilasuit** [PoshCode/ModuleBuilder#23]
https://github.com/PoshCode/ModuleBuilder/blob/7373c0f5e2dee5f41a8bfaaee34faefd43981e59/bootstrap.ps1#L13 shows PSDepends not PSDepend

**Comment by Jaykul** [comment]
Thanks. I wonder if that will fix the build... *sigh*

**Comment by Jaykul** [comment]
Also, how the heck did you create that issue?

**Comment by Jaykul** [comment]
https://github.com/PoshCode/ModuleBuilder/blob/dev/bootstrap.ps1#L13

**Comment by Jaykul** [comment]
https://github.com/PoshCode/ModuleBuilder/blob/715e66f4a19800c8679c62fae080eab238339fd6/bootstrap.ps1#L13

**Comment by Jaykul** [comment]
https://github.com/AtlassianPS/AtlassianPS.Configuration/blob/6fc739f7cb7f131600524440d2f53f43369b9529/Tools/BuildTools.psm1#L392-L446
