### ISSUE TITLE
bootstrap.ps1 error

### ISSUE THREAD

**Issue by MarkRobertJohnson** [PoshCode/ModuleBuilder#34]
bootstrap.ps1 causes the following error:

> Install-Module : Cannot validate argument on parameter 'MaximumVersion'. The argument is null. Provide a valid value
> for the argument, and then try running the command again.

It is because the cast to [ModuleSpecification[]] of the RequiredModules, creates empty properties for Version, MaximumVersion, and Guid

**Comment by LaurentDardenne** [comment]
An another issue  with bootstrap.ps1: 
![image](https://user-images.githubusercontent.com/4894452/49582821-7cbc0280-f956-11e8-9212-51311ece88dd.png)
```powershell
gcm -name 'Export-Metadata'

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Export-Metadata                                    2.0.1      BuildHelpers
```
Just add the parameter -AllowClobber :
```Powershell
    $RequiredModules | Install-Module -Scope $Scope -Repository PSGallery -SkipPublisherCheck -Verbose -AllowClobber     
```

**Comment by Jaykul** [comment]
@MarkRobertJohnson PS version?

@LaurentDardenne dirty rotten @RamblingCookieMonster stealing my commands and shipping them in his own module without even changing the name!

**Comment by Jaykul** [comment]
This should be fixed now that we've moved to using `Install-RequiredModule` right?

**Comment by LaurentDardenne** [comment]
It ok for me, thanks :
![image](https://user-images.githubusercontent.com/4894452/59526397-21f0fe00-8ed9-11e9-937c-6837e48a237b.png)
