### ISSUE TITLE
-Prefix or -Suffix dot not throw an exception when a file do not exist

### ISSUE THREAD

**Issue by LaurentDardenne** [PoshCode/ModuleBuilder#40]
With this setting:
```PowerShell
@{
    Path = "MyModule.psd1"
    OutputDirectory = "C:\temp\Delivery\MyModule"
    VersionedOutputDirectory = $true
    CopyDirectories=@('.\Demos','.\fr-FR','.\TypeData')
    Prefix='.\Initialzation.ps1' 
    Suffix='.\Finalization.ps1'
}     
```
If the file does not exist, no errors are triggered:
![image](https://user-images.githubusercontent.com/4894452/49684868-224baf00-fada-11e8-8c6a-f4ea4c644a7e.png)

If I correct the file name, the addition is done correctly :
![image](https://user-images.githubusercontent.com/4894452/49684871-2d9eda80-fada-11e8-85d1-c34a23f29856.png)

The error exists but is not displayed  : 
![image](https://user-images.githubusercontent.com/4894452/49684804-4c50a180-fad9-11e8-9a93-0fbcd593e93d.png)
Same behavior with Suffix :
![image](https://user-images.githubusercontent.com/4894452/49684909-b1f15d80-fada-11e8-8b07-2224c441bac0.png)

**Comment by SimonWahlin** [comment]
I think this is somewhat an expected behavior since the Prefix and Suffix will add a file - if it exists, else it will add the value of Prefix and/or Suffix to your compiled .psm1 as explained on [this line](https://github.com/PoshCode/ModuleBuilder/blob/0ca3cc66d89fe0acc4ba644b53d3aba8e2fa7eac/Source/Public/Build-Module.ps1#L109) 

So if the file does not exist, the compiled psm1 will start with:
```PowerShell
#Region 'PREFIX' 0
.\Initialzation.ps1
#EndRegion 'PREFIX'
```
For me personally I can't come up with a scenario where I would want/need to put the actual prefix/suffix code directly into my build.psd1 instead of referencing a file. My suggestion is therefor to remove support for code in prefix/suffix part of build.psd1 and only support file paths. If file isn't found an error should be thrown, even if it is a breaking change.

The case for this only gets stronger if we add support for build.ps1 outside of the source folder (#49).

I would be glad to submit a PR for this.

**Comment by Jaykul** [comment]
My _main_ use for this feature is to specify my exports in the build.psd1, or to add a common `using` statement, without needing a whole file for one line of code:

```powershell
Prefix = "using namespace System.Collections.Generic"
Suffix = "Export-ModuleMember *-* -Alias *"
```

However, I can see how it's a problem if you make a typo in a file name....

I'd be willing to either _add_ a "PrefixFile" and "SuffixFile" which explicitly fail if the file doesn't exist, or to change this to behave that way, I suppose. Whichever suits us all the best. Thoughts?

**Comment by Jaykul** [comment]
How would you determine whether it's a path or not?
![image](https://user-images.githubusercontent.com/192942/51617401-27ce4e80-1efa-11e9-8116-da30fd8978b0.png)

**Comment by ld0614** [comment]
I'm not sure if this is exactly related but I tripped into this issue when attempting to define a cmdlet prefix using the psd1 file
```
DefaultCommandPrefix = 'FireOne'
```

This caused the top of the script to include the data

```
#Region 'PREFIX' 0
FireOne
#EndRegion 'PREFIX'
```

which obviously broke the module, is there any way to use DefaultCommandPrefix correctly with ModuleBuilder?

**Comment by Jaykul** [comment]
Ouch, @ld0614 -- that's definitely related, and would turn this from a "nice to have, but can fix with better docs" into a "oh, no, it's horrible, fix it, fix it now!" 😉

Are you saying that you put a `DefaultCommandPrefix` in your `build.psd1`, or that ModuleBuilder picked it up from your module manifest **until** you specified the Prefix in your `build.psd1`?

**Comment by ld0614** [comment]
If `DefaultCommandPrefix` **is** in MyModule.psd1 and there is **no** `Prefix` in build.psd1 then ModuleBuilder inserts the result of `DefaultCommandPrefix` into the top of MyModule.psm1.  Module commands are not prefixed correctly.

If `DefaultCommandPrefix` **is not** in MyModule.psd1 and there **is** `Prefix` in build.psd1 then ModuleBuilder inserts the result of `Prefix` into the top of MyModule.psm1.  Module commands are not prefixed correctly.

If `DefaultCommandPrefix` **is** in MyModule.psd1 and there **is** `Prefix` in build.psd1 (although not valid) then ModuleBuilder inserts the result of `Prefix` into the top of MyModule.psm1.  Module commands are not prefixed correctly.

If `DefaultCommandPrefix` **is** in MyModule.psd1 and there **is** `Prefix` in build.psd1 then ModuleBuilder inserts the result of `Prefix` into the top of MyModule.psm1.  Module commands are prefixed correctly.

**Comment by Jaykul** [comment]
Ok, let's call that critical then ;-)

**Comment by ld0614** [comment]
@Jaykul Thanks for the fast fix, unfortunately I believe that this is causing the prefix in build.psd1 to be ignored.  I have the following configuration for testing:

```
    Prefix = ".\_GlobalScope.ps1"
    Suffix = ".\_GlobalScope.ps1"
```

Unfortunately the code is only added at the bottom, if the suffix command is removed then _GlobalScope.ps1 isn't copied into the module file at all.  To confirm that this was a regression I retested against the version available from the PowerShell Gallery which worked as expected.  Module commands are being prefixed correctly however 😄

**Comment by Jaykul** [comment]
For what it's worth, I was not able to reproduce this. I added [this regression test](https://github.com/PoshCode/ModuleBuilder/blob/84709a8e27f22513c0af9eadb4bd255762ee1807/Tests/Integration/Source1.Tests.ps1#L176) to the integration tests.

If anyone's seeing anything like this, please open a new bug.
