### ISSUE TITLE
Bootstrap script - requiredversion

### ISSUE THREAD

**Issue by stefanstranger** [PoshCode/ModuleBuilder#42]
In the RequiredModules.psd1 the requiredversion is used to get the 'correct' PowerShell Modules installed. I already have some newer module versions installed on my system. 

Would it be an idea to use minimumversion?

The build.ps1 script does not specially imports the PowerShell Module version configured in the RequiredModules.psd1 if I'm correct.

**Comment by gaelcolas** [comment]
In the ModuleSpecification constructor it actually expects `ModuleVersion` for minimum version (confusing)
But yeah, that sounds like a quick and easy change...
PR coming
