### ISSUE TITLE
About_ModuleBuilder is not found

### ISSUE THREAD

**Issue by Stephanevg** [PoshCode/ModuleBuilder#43]
There seems to be no "About_ModuleBuilder" file.

![image](https://user-images.githubusercontent.com/6302961/51074019-b8469c80-1679-11e9-9caa-6bb69750b749.png)

**Comment by LaurentDardenne** [comment]
It is located [here](https://github.com/PoshCode/ModuleBuilder/blob/master/ReadMe.md)

**Comment by Stephanevg** [comment]
thats the readme, and its on the internet ;)

**Comment by kilasuit** [comment]
It probably could be packaged into an about_ file that goes with the module at install time

**Comment by Jaykul** [comment]
Hmm. Copying ReadMe to About was part of `Build-Module` originally, I refactored it to [CopyReadMe](https://github.com/PoshCode/ModuleBuilder/blob/master/Source/Private/CopyReadme.ps1).

It looks like I removed the call to that in #434281d9144333bb55044a41b897eefffac5d919 ... not sure why. 

I think I should probably just put that back.

**Comment by Jaykul** [comment]
Yeah, I think the real reason I took it out was that I decided that it should not be in `Build-Module` ... but instead, in a separate step (i.e. PlatyPS's `Update-MarkdownHelp`)

**Comment by Jaykul** [comment]
Leaving this open until we actually ship it, because I'm having trouble keeping things straight having just got back from vacation.
