### ISSUE TITLE
Add support for Build.psd1 outside Source

### ISSUE THREAD

**Issue by gaelcolas** [PoshCode/ModuleBuilder#49]
I like having my `Build.psd1` outside (one folder up) the source, so that it's clear everything in source will be part of the module.

The documentation makes it [clear it's a requirement](https://github.com/PoshCode/ModuleBuilder/blob/master/Source/Private/InitializeBuild.ps1#L17), but I don't see a good reason not to support this.

Currently the limitation seems to be coming from [InitializeBuild](https://github.com/PoshCode/ModuleBuilder/blob/master/Source/Private/InitializeBuild.ps1).

Would you be accept a PR that supports having the Build.psd1 in a different folder than the Module Manifest?

**Comment by Jaykul** [comment]
I have the same problem with this as the request to do away with the build.psd1 completely. It's basically our project file. It's location is a _source_ of truth: it defines the root of the project source code, and path resolution happens relative to it's location...

Clearly the two requests are related, and if we wanted to, we could do both -- but then we would end up needing _another_ path **parameter** to TELL US where the source is, which makes the default simple scenario more complicated.

**Comment by Jaykul** [comment]
For example, look at how we deal with the SourceDirectories: https://github.com/PoshCode/ModuleBuilder/blob/ab29cc3128b0a5c8dc9dbc6af8dec4707b8f6866/Source/Public/Build-Module.ps1#L197

How will you define ModuleBase?

**Comment by gaelcolas** [comment]
I feel that the logic should be:
- if $SourcePath resolves to a Build.psd1 and it has a Path to the Module manifest
   Then the Module manifest will 'override' SourcePath for the module source
In any other case, the SourcePath will be used as it is currently.
Will try to send a PR to illustrate this tomorrow morning.

**Comment by gaelcolas** [comment]
Hi @Jaykul, How's #51 logic in principle?

1. That does mean we're now resolving the source directory based on the ModuleManifest. Are you ok with that?
2. Alternatively we could also add an override key for that in the `Build.psd1`? I think it's unlikely someone would put the Module Manifest outside the Source folder.

There's many issue with _that_ implementation, like using the `$buildRoot` variable name (conflict with IB), lack of validation that was done in ResolveModuleSource... but that's 'implementation details' for now.

**Comment by gaelcolas** [comment]
Pinging @Jaykul for comment.
Ignoring the other request to do away from even needing the PSD1 completely, related but independent.

I think we could have the `Build.psd1` placed outside of `source` if we implement the following logic.
1. If nothing is specified to the `Build-Module` command: Assume `$SourcePath` is Current location (no change to current behaviour)
2. If `SourcePath` parameter is used, use this as `$SourcePath` (no change), and run the following init steps (where the change is)

a. If the param `Build-Module -SourcePath` points to a `Build.psd1`, outside of the source folder, you **must** specify the location of the module source files & manifest (**new behaviour**) in the `SourcePath` property of the `Build.psd1` (otherwise it will fail as per c.).
  This is **the only case where you can have a `Build.psd1` outside of the source folder**. We can use the fact that the Leaf of the `-SourcePath` parameter matches 'Build' **AND** that `SourcePath =` specified in `Build.psd1` resolves.

b.1. If the param `Build-Module -SourcePath` points to a `Build.psd1`, alongside with the sources, and the `SourcePath =` is defined in `Build.psd1`, existing behaviour prevails (Resolve module manifest in same parent folder).
b.2. If the param `Build-Module -SourcePath` points to a `ModuleManifest`, existing behaviour prevails (Resolve `Build.psd1` in same parent folder).
c. If the param `Build-Module -SourcePath` points to a `Build.psd1`, and that `Build.psd1` does not define `SourcePath =`, the initialisation step will resolve the module manifest in the same folder parent folder than `Build.psd1`, and fail if unavailable.

I appreciate that will change a bit the current way the private functions (`InitializeBuild` & `ResolveModuleSource`) are being called and the validation executed, but I don't think that's a major issue.

Any objections to this feature based on this principle?

**Comment by Jaykul** [comment]
The problem isn't with finding the module, the problem is what relative paths mean. We have to be able to use relative paths so we can share projects with other people. Right now, we assume that build.psd1 is in the source root, and so all paths in it are relative to the source root -- or rather, relative to the location of build.psd1:

https://github.com/PoshCode/ModuleBuilder/blob/7cb1c4f4c976b96fb07aae105899699fc67afb8f/Source/Private/InitializeBuild.ps1#L76-L80

So if we move build.psd1, given a call like this:

`Build-Module .\Projects\Modules\MyModuleOne\build.psd1` 

1. If build.psd1 has `SourcePath = "..\..\Module1\Source"` what is it relative to?
2. If build.psd1 also has `OutputDirectory = "..\"` what is _that_ relative to?

Where did it look for source, and where did the output end up, and how did we make that happen?

**Comment by gaelcolas** [comment]
Yes, PR #54 addresses this by:
1. Finding the Build Manifest Build.psd1
2. [Pushing location to its parent](https://github.com/gaelcolas/ModuleBuilder/blob/feature/buildpsd1out/Source/Private/GetBuildInfo.ps1#L64) (so resolutions will be relative to `Build.psd1`)
3. Resolving `OutputDirectory` & `SourcePath` defined in the `Build.psd1` [relative to this new location](https://github.com/gaelcolas/ModuleBuilder/blob/feature/buildpsd1out/Source/Private/InitializeBuild.ps1#L51-L56)
4. Pushing to [The Module Base](https://github.com/gaelcolas/ModuleBuilder/blob/feature/buildpsd1out/Source/Public/Build-Module.ps1#L184) location for the remaining of the merge files and copy directory steps (`$OutputDirectory` and other **resolved** path earlier are already rooted)

**Comment by gaelcolas** [comment]
For clarity that would look like this:
```PowerShell
@{
    # Relative to Build.psd1
    Path = "ModuleBuilder.psd1"

    # Relative to Build.psd1
    OutputDirectory = "..\"

    VersionedOutputDirectory = $true

    # Relative to ModuleBase
    CopyDirectories = @('en-US')
   # SourceDirectories
}
```

**Comment by Jaykul** [comment]
So we would define `ModuleBase` as "where the `Path` points to" but change some paths to resolve relative to a _different_ base.

**Two different base locations** used for the relative paths specified in the file seems confusing. Is it really worth it? I feel like I need more opinions than just you and I.

**Comment by gaelcolas** [comment]
It sounds like a big deal, but it makes a difference only when you actively put your build.psd1 and module manifest in different places.
So it's an add-on more than anything else :)

It's easy to have them all relative to the Build.psd1, although I don't think it's a good idea.

**Comment by Jaykul** [comment]
Can you name any other system which works like that? I mean, have you ever tried putting a .csproj file anywhere other than in the root (or a direct ancestor)?

**Comment by gaelcolas** [comment]
Projects who are not built based on the IDE that goes with them... Or generated by tooling requiring specific paths...
ANT & its Build.xml?
Makefiles? - It's a convention or preference, sometimes driven by the tools using them...

Obviously, I'm only really interested in the direct Ancestor (root of the project). My main argument is that this is where the configuration Data is visible for the project. 
We already need config data (and a file for each) of those: AppVeyor, AzurePipelines, CodeCov, RequiredModules, nuget packages... All at the root of the project...
Having other configuration files in sub folders seems to make it less visible, less discoverable, raising the bar of entry.

I think for CSPROJ and SLN it's specific to the semantic and segregation that has been done by Visual Studio for C# projects. What percentage of users create those by hand, and change them by hand? They're **already visible** because of the GUI, **despite** their location.

**Comment by gaelcolas** [comment]
Updated the PR so that now every path is relative to ModuleManifest, and that it's clearer that you can override the ModuleManifest's path in the Build.psd1
```powershell
@{
    ModuleManifest = "ModuleBuilder.psd1"
    # Subsequent relative paths are to the ModuleManifest
    OutputDirectory = "..\"
    VersionedOutputDirectory = $true
    CopyDirectories = @('en-US')
}
```
