### ISSUE TITLE
use #Region keyword

### ISSUE THREAD

**Issue by Jaykul** [PoshCode/ModuleBuilder#5]
**As a** VS, Code or ISE user
**In order to** improve productivity when working with output
**I need** to be able to collapse per-file content

---

### Replace the `# BEGIN ` and `# END ` text with `#REGION SOURCE: ` and `#ENDREGION SOURCE: ` 

Using `#REGION` would provide some utility to anyone who opens the output file in an editor, but would not change our ability to extract information (decompile or lookup). However, we need a second magic keyword to make sure we aren't confused by the possible use of normal regions _within_ the source.

**Important:** this requires changes to `Build-Module` and also `Convert-CodeCoverage` -- and any other potential line-conversion functions.

We need a `ConvertLineNumber` function based on [lines 43 and 56](https://github.com/PoshCode/ModuleBuilder/blob/master/Source/Public/Convert-CodeCoverage.ps1#L42-L60) of the `Convert-CodeCoverage` function --- we're going to need the same logic for converting error message stack traces, etc. Just make sure not to loose the ability to _cache_ the source data, even if that means storing it temporarily in a `$Script:` scope variable.

**Comment by gaelcolas** [comment]
It seems that you've already done this one, or am I missing something?

**Comment by Jaykul** [comment]
Yes I have! 👍
