### ISSUE TITLE
SourceDirectories can't be changed in build.ps1

### ISSUE THREAD

**Issue by GreatTeacherBasshead** [PoshCode/ModuleBuilder#55]
When I change the default `SourceDirectories` list in build.ps1:
`
@{
	SourceDirectories = @("Private", "Public", "Data")
}
`

It doesn't work. Still uses the default value from ModuleBuilder.ps1 ("Enum", "Classes", "Private", "Public").

I found that using `$ModuleInfo.SourceDirectories` instead of `$SourceDirectories` in line 659 in ModuleBuilder.ps1 like this:
`$AllScripts = Get-ChildItem -Path @($ModuleInfo.SourceDirectories).ForEach{ Join-Path $ModuleInfo.ModuleBase $_ } -Filter *.ps1 -Recurse -ErrorAction SilentlyContinue`
instead of
`$AllScripts = Get-ChildItem -Path $SourceDirectories.ForEach{ Join-Path $ModuleInfo.ModuleBase $_ } -Filter *.ps1 -Recurse -ErrorAction SilentlyContinue`
solves the problem.

I'm just not sure if I'm doing this right... If that's ok, I can contribute and create a pull request.

**Comment by Jaykul** [comment]
That looks right.

**Comment by Jaykul** [comment]
TODO: Add tests to ...
1. Prove this works
2. Ensure it doesn't get broken by future changes (e.g. #54)
