### ISSUE TITLE
an example in Readme.md does not work as intended

### ISSUE THREAD

**Issue by HoppingJ** [PoshCode/ModuleBuilder#60]
While following the readme instructions, the module was not installed correctly.  I know the powershell command was qualified with "_something like this_" but it's so close to correct that I wanted to help the next guy.  Using the instructions as is, only created a folder "1.0.0" in Modules\ModuleBuilder.  When I added the -Recurse switch as shown below then the contents of the module were copied into the destination as I believe the intention was:

Original:
`$UserModules = Join-Path (Split-Path $Profile.CurrentUserAllHosts) "Modules\ModuleBuilder"
New-Item $UserModules -Type Directory -Force
Copy-Item (.\build.ps1) -Destination $UserModules -Force`

Suggested:
`$UserModules = Join-Path (Split-Path $Profile.CurrentUserAllHosts) "Modules\ModuleBuilder"
New-Item $UserModules -Type Directory -Force
Copy-Item (.\build.ps1) -Destination $UserModules -Force -Recurse`

**Comment by Jaykul** [comment]
Fixed
