### ISSUE TITLE
SemVer can't handle pre-release with dash in the name

### ISSUE THREAD

**Issue by Jaykul** [PoshCode/ModuleBuilder#70]
If I call `Build-Module ... -Semver 1.2.3-pre-release` I lose the "-release" part

**Comment by gaelcolas** [comment]
but that's not SemVer 2.0.0 compatible iirc...?
So is that really a bug?

**Comment by Jaykul** [comment]
That's incorrect. From semver.org (emphasis mine):

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics **and hyphen** [0-9A-Za-z-].
