### ISSUE TITLE
Question about Modules with .Net Assemblies

### ISSUE THREAD

**Issue by mattmcnabb** [PoshCode/ModuleBuilder#72]
Is there any support or guidance for modules with dependent .Net assemblies? For instance, I have a module with a .Net Core project and PowerShell module content, and these need to be compiled together.

Alternatively, would it be better to have a `dotnet build` step prior to invoking `Build-Module`?

Thanks!

**Comment by Jaykul** [comment]
What I'm doing is `dotnet build -c Release` before a `Build-Module` step, and in the build.psd1 I use `CopyDirectories` to move the dll into the output. 

See [this branch](https://github.com/Jaykul/PowerShellLoggingModule/blob/jaykul/AzPipeline/) as an example, specifically, the [build.ps1](https://github.com/Jaykul/PowerShellLoggingModule/blob/jaykul/AzPipeline/Build.ps1) or the [azure-pipelines.yaml](https://github.com/Jaykul/PowerShellLoggingModule/blob/jaykul/AzPipeline/azure-pipelines.yml) and the [build.psd1](https://github.com/Jaykul/PowerShellLoggingModule/blob/jaykul/AzPipeline/Module/PowerShellLogging/build.psd1)

**Comment by mattmcnabb** [comment]
Got it, thanks!
