### ISSUE TITLE
Install-RequiredModule.ps1 is missing

### ISSUE THREAD

**Issue by FISHMANPET** [PoshCode/ModuleBuilder#75]
The README implies the script should live in the root of the repo, and it appears that was once true.  But for some reason in 6e564ddc0b3838fe22c5aab329ade7966b514fa4 it was deleted without explanation.  I can't find it anywhere else in this org, was it removed for a reason?  Should it be restored?  The version deleted there seems to match what's currently published in the gallery but if that's the case where is the source code for the gallery script living?  That script links to this repo so this seems like a mistake that it was removed rather than an intentional decision.

**Comment by gaelcolas** [comment]
True, [it's available here on the Gallery in the meantime](https://www.powershellgallery.com/packages/Install-RequiredModule/4.0.6).
I think I flagged this up to @Jaykul before, and that's because he hasn't finished moving it to this repo.

**Comment by Jaykul** [comment]
Yes, [the source is the script itself](https://www.powershellgallery.com/packages/Install-RequiredModule/4.0.6/Content/Install-RequiredModule.ps1). I am working on a small but significant change, but you're right that I need to publish the repository I moved it to. I'll try to do that today or tomorrow.

**Comment by bravo-kernel** [comment]
refs #77

**Comment by Jaykul** [comment]
OK, Install-RequiredModule is in it's own repo now. Still WIP but here: [/Jaykul/RequiredModules](https://github.com/Jaykul/RequiredModules)
