### ISSUE TITLE
Please document dependency on gitversion

### ISSUE THREAD

**Issue by FISHMANPET** [PoshCode/ModuleBuilder#76]
the bootstrap build.ps1 file uses something called `gitversion` which is not listed in RequiredModules and I have no idea what it is or how to get it.

I'm aware of the gitversion project but this `gitversion` uses Powershell style parameter passing but doesn't follow Powershell cmdlet naming functions, and also I can't find any reference to a `showvariable` parameter in the gitversion documentation.  I also can't find anything in the powershell gallery related to gitversion.  Looking through the sourcecode of gitversion there does appear to be a `/showvariable` parameter but it also requires `/output json` which isn't being specified here so I don't think this is just merely the gitversion executable.

And IF IT IS just the gitversion executable, that needs to be called out in the documentation.

**Comment by gaelcolas** [comment]
Yes, it is (just the gitversion executable).

[Some cmd tool allow this style of params](https://superuser.com/questions/745951/dash-or-slash-in-batch-file), such as `shutdown.exe` (both `shutdown -s -t 0` and `shutdown /s /t 0` works).

My version of gitversion (`4.0.0+Branch.master.Sha.e715eb5dd515037d90a257f527e62442cae8c1c5`) does show this parameter, here's the help line (`gitversion -?`)
```
/showvariable   Used in conjuntion with /output json, will output just a particular variable.
                    eg /output json /showvariable SemVer - will output `1.2.3+beta.4`
```

It seems that `/output json` is not required.

Yes, fixing the doc would be great, could you edit your title to be more explicit? Thanks.
